import type { Report, Agency, Category, User, Notification, AuditLog, RoutingRule } from "./types";

export const agencies: Agency[] = [
  { id: "1", name: "Dinas PUPR", code: "PUPR", type: "Teknis", status: "Aktif", adminCount: 5, reportCount: 142, description: "Dinas Pekerjaan Umum dan Penataan Ruang" },
  { id: "2", name: "Dinas Lingkungan Hidup", code: "DLH", type: "Teknis", status: "Aktif", adminCount: 3, reportCount: 89, description: "Dinas Lingkungan Hidup Daerah" },
  { id: "3", name: "BPBD", code: "BPBD", type: "Penanggulangan", status: "Aktif", adminCount: 4, reportCount: 56, description: "Badan Penanggulangan Bencana Daerah" },
  { id: "4", name: "Dinas Perhubungan", code: "DISHUB", type: "Teknis", status: "Aktif", adminCount: 3, reportCount: 38, description: "Dinas Perhubungan Daerah" },
  { id: "5", name: "Dinas Sosial", code: "DINSOS", type: "Sosial", status: "Aktif", adminCount: 2, reportCount: 21, description: "Dinas Sosial Daerah" },
  { id: "6", name: "Dinas Kesehatan", code: "DINKES", type: "Kesehatan", status: "Nonaktif", adminCount: 0, reportCount: 12, description: "Dinas Kesehatan Daerah" },
];

export const categories: Category[] = [
  { id: "1", name: "Jalan & Infrastruktur", icon: "road", agency: "Dinas PUPR", priority: "Tinggi", status: "Aktif", reportCount: 87, color: "blue" },
  { id: "2", name: "Kebersihan & Sampah", icon: "trash", agency: "Dinas Lingkungan Hidup", priority: "Sedang", status: "Aktif", reportCount: 64, color: "green" },
  { id: "3", name: "Penerangan Jalan", icon: "lamp", agency: "Dinas PUPR", priority: "Sedang", status: "Aktif", reportCount: 45, color: "yellow" },
  { id: "4", name: "Drainase & Banjir", icon: "water", agency: "BPBD", priority: "Tinggi", status: "Aktif", reportCount: 38, color: "sky" },
  { id: "5", name: "Pohon & Taman", icon: "tree", agency: "Dinas Lingkungan Hidup", priority: "Rendah", status: "Aktif", reportCount: 29, color: "emerald" },
  { id: "6", name: "Trotoar & Fasilitas", icon: "walk", agency: "Dinas PUPR", priority: "Sedang", status: "Aktif", reportCount: 33, color: "violet" },
  { id: "7", name: "Bencana Alam", icon: "warning", agency: "BPBD", priority: "Urgent", status: "Aktif", reportCount: 18, color: "red" },
  { id: "8", name: "Lingkungan & Polusi", icon: "leaf", agency: "Dinas Lingkungan Hidup", priority: "Tinggi", status: "Aktif", reportCount: 25, color: "teal" },
];

export const reports: Report[] = [
  {
    id: "RPT-2024-001",
    title: "Jalan Berlubang di Jalan Raya Banyakan",
    category: "Jalan & Infrastruktur",
    categoryId: "1",
    description: "Terdapat lubang besar di tengah jalan raya Banyakan sepanjang kurang lebih 2 meter dengan kedalaman sekitar 30 cm. Sangat berbahaya bagi pengendara, terutama di malam hari. Sudah ada 2 kejadian kecelakaan akibat lubang ini.",
    location: "Jl. Raya Banyakan, Kediri",
    district: "Banyakan",
    date: "2024-12-15",
    status: "Diproses",
    priority: "Tinggi",
    agency: "Dinas PUPR",
    agencyCode: "PUPR",
    reporter: "Anonim7283640192",
    isAnonymous: true,
    photos: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=800&h=500&fit=crop&auto=format",
    ],
    supportCount: 47,
    commentCount: 12,
    isSupported: true,
    isSaved: false,
    lat: -7.849,
    lng: 112.015,
    timeline: [
      { status: "Dikirim", date: "15 Des 2024", time: "08:32", description: "Laporan dikirim oleh warga" },
      { status: "Diverifikasi", date: "16 Des 2024", time: "10:15", description: "Laporan diverifikasi oleh Admin PUPR", actor: "Admin PUPR" },
      { status: "Diproses", date: "17 Des 2024", time: "09:00", description: "Tim lapangan ditugaskan untuk penanganan", actor: "Admin PUPR" },
    ],
    governmentResponse: "Terima kasih atas laporannya. Tim kami sedang dalam proses perbaikan jalan. Perkiraan selesai dalam 3 hari kerja.",
    responseDate: "17 Des 2024",
    internalNotes: "Prioritas tinggi. Koordinasi dengan tim lapangan sudah dilakukan.",
  },
  {
    id: "RPT-2024-002",
    title: "Sampah Menumpuk di Area Pasar Baru",
    category: "Kebersihan & Sampah",
    categoryId: "2",
    description: "Sampah menumpuk sangat tinggi di sekitar area Pasar Baru sudah lebih dari 5 hari tidak diangkut. Menimbulkan bau tidak sedap dan menjadi sarang penyakit. Warga sekitar sangat terganggu.",
    location: "Pasar Baru, Kediri",
    district: "Kota",
    date: "2024-12-14",
    status: "Dikirim",
    priority: "Sedang",
    agency: "Dinas Lingkungan Hidup",
    agencyCode: "DLH",
    reporter: "Anonim5019384726",
    isAnonymous: true,
    photos: [
      "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&h=500&fit=crop&auto=format",
    ],
    supportCount: 83,
    commentCount: 24,
    isSupported: false,
    isSaved: true,
    lat: -7.818,
    lng: 112.011,
    timeline: [
      { status: "Dikirim", date: "14 Des 2024", time: "14:20", description: "Laporan dikirim oleh warga" },
    ],
  },
  {
    id: "RPT-2024-003",
    title: "Lampu Penerangan Jalan Mati di Jl. Sudirman",
    category: "Penerangan Jalan",
    categoryId: "3",
    description: "Sebanyak 8 titik lampu penerangan jalan umum (PJU) di sepanjang Jl. Sudirman dalam kondisi mati sudah 2 minggu. Jalan gelap gulita di malam hari dan rawan kejahatan.",
    location: "Jl. Sudirman, Kediri",
    district: "Mojoroto",
    date: "2024-12-10",
    status: "Diverifikasi",
    priority: "Sedang",
    agency: "Dinas PUPR",
    agencyCode: "PUPR",
    reporter: "Anonim3847562910",
    isAnonymous: true,
    photos: [
      "https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=800&h=500&fit=crop&auto=format",
    ],
    supportCount: 31,
    commentCount: 8,
    isSupported: false,
    isSaved: false,
    lat: -7.821,
    lng: 112.008,
    timeline: [
      { status: "Dikirim", date: "10 Des 2024", time: "19:45", description: "Laporan dikirim oleh warga" },
      { status: "Diverifikasi", date: "11 Des 2024", time: "08:30", description: "Laporan diverifikasi oleh Admin PUPR", actor: "Admin PUPR" },
    ],
    governmentResponse: "Laporan sudah diterima. Akan segera kami tindaklanjuti.",
    responseDate: "11 Des 2024",
  },
  {
    id: "RPT-2024-004",
    title: "Saluran Air Tersumbat di Kelurahan Kebonsari",
    category: "Drainase & Banjir",
    categoryId: "4",
    description: "Saluran air utama di kelurahan Kebonsari tersumbat sampah dan lumpur. Mengakibatkan air meluap ke jalan saat hujan dan menggenangi rumah warga sekitar.",
    location: "Kel. Kebonsari, Kediri",
    district: "Pesantren",
    date: "2024-12-01",
    status: "Selesai",
    priority: "Tinggi",
    agency: "Dinas PUPR",
    agencyCode: "PUPR",
    reporter: "Anonim6192847305",
    isAnonymous: true,
    photos: [
      "https://images.unsplash.com/photo-1527359443443-84a48aec73d2?w=800&h=500&fit=crop&auto=format",
    ],
    supportCount: 129,
    commentCount: 35,
    isSupported: true,
    isSaved: true,
    lat: -7.851,
    lng: 112.025,
    timeline: [
      { status: "Dikirim", date: "01 Des 2024", time: "07:15", description: "Laporan dikirim oleh warga" },
      { status: "Diverifikasi", date: "02 Des 2024", time: "09:00", description: "Laporan diverifikasi oleh Admin PUPR", actor: "Admin PUPR" },
      { status: "Diproses", date: "03 Des 2024", time: "08:00", description: "Tim drainase ditugaskan ke lokasi", actor: "Admin PUPR" },
      { status: "Selesai", date: "05 Des 2024", time: "16:30", description: "Pembersihan saluran selesai dilakukan", actor: "Admin PUPR" },
    ],
    governmentResponse: "Perbaikan saluran drainase telah selesai dilaksanakan. Saluran air kini berfungsi normal.",
    responseDate: "05 Des 2024",
    resolutionEvidence: "https://images.unsplash.com/photo-1504711331083-9c895941bf81?w=800&h=500&fit=crop&auto=format",
  },
  {
    id: "RPT-2024-005",
    title: "Pohon Tumbang di Jalan Utama Pantura",
    category: "Pohon & Taman",
    categoryId: "5",
    description: "Pohon besar tumbang akibat angin kencang dan menutup sebagian jalan utama Pantura. Perlu penanganan segera untuk keselamatan lalu lintas.",
    location: "Jl. Pantura, Kediri",
    district: "Ngasem",
    date: "2024-12-18",
    status: "Selesai",
    priority: "Urgent",
    agency: "BPBD",
    agencyCode: "BPBD",
    reporter: "Anonim9047251836",
    isAnonymous: true,
    photos: [
      "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&h=500&fit=crop&auto=format",
    ],
    supportCount: 210,
    commentCount: 41,
    isSupported: false,
    isSaved: false,
    lat: -7.805,
    lng: 112.003,
    timeline: [
      { status: "Dikirim", date: "18 Des 2024", time: "14:10", description: "Laporan darurat dikirim oleh warga" },
      { status: "Diverifikasi", date: "18 Des 2024", time: "14:25", description: "Verifikasi cepat oleh Admin BPBD", actor: "Admin BPBD" },
      { status: "Diproses", date: "18 Des 2024", time: "15:00", description: "Tim BPBD diberangkatkan ke lokasi", actor: "Admin BPBD" },
      { status: "Selesai", date: "18 Des 2024", time: "17:30", description: "Pohon tumbang berhasil dipindahkan, jalan kembali lancar", actor: "Admin BPBD" },
    ],
    governmentResponse: "Tim BPBD telah berhasil menangani pohon tumbang. Jalan kini sudah dapat dilalui kembali.",
    responseDate: "18 Des 2024",
  },
  {
    id: "RPT-2024-006",
    title: "Trotoar Rusak di Alun-alun Kota",
    category: "Trotoar & Fasilitas",
    categoryId: "6",
    description: "Paving trotoar di area alun-alun kota banyak yang retak dan terangkat. Membahayakan pejalan kaki, terutama lansia dan anak-anak.",
    location: "Alun-alun Kota Kediri",
    district: "Kota",
    date: "2024-12-12",
    status: "Diproses",
    priority: "Sedang",
    agency: "Dinas PUPR",
    agencyCode: "PUPR",
    reporter: "Anonim4728301956",
    isAnonymous: true,
    photos: [
      "https://images.unsplash.com/photo-1519923834699-ef0b7eda4b98?w=800&h=500&fit=crop&auto=format",
    ],
    supportCount: 55,
    commentCount: 14,
    isSupported: false,
    isSaved: false,
    lat: -7.816,
    lng: 112.012,
    timeline: [
      { status: "Dikirim", date: "12 Des 2024", time: "10:00", description: "Laporan dikirim oleh warga" },
      { status: "Diverifikasi", date: "13 Des 2024", time: "11:00", description: "Laporan diverifikasi oleh Admin PUPR", actor: "Admin PUPR" },
      { status: "Diproses", date: "15 Des 2024", time: "08:30", description: "Proses perbaikan dimulai", actor: "Admin PUPR" },
    ],
  },
  {
    id: "RPT-2024-007",
    title: "TPS Liar di Kawasan Pemukiman Warga",
    category: "Kebersihan & Sampah",
    categoryId: "2",
    description: "Ada tempat pembuangan sampah liar di gang belakang perumahan. Warga membuang sampah sembarangan di lokasi tersebut.",
    location: "Perum. Griya Indah, Kediri",
    district: "Pesantren",
    date: "2024-12-08",
    status: "Ditolak",
    priority: "Rendah",
    agency: "Dinas Lingkungan Hidup",
    agencyCode: "DLH",
    reporter: "Anonim8163049572",
    isAnonymous: true,
    photos: [],
    supportCount: 8,
    commentCount: 3,
    isSupported: false,
    isSaved: false,
    lat: -7.845,
    lng: 112.022,
    timeline: [
      { status: "Dikirim", date: "08 Des 2024", time: "15:00", description: "Laporan dikirim oleh warga" },
      { status: "Ditolak", date: "09 Des 2024", time: "10:00", description: "Ditolak: Lokasi tidak dalam kewenangan instansi. Laporan tidak disertai bukti foto.", actor: "Admin DLH" },
    ],
  },
  {
    id: "RPT-2024-008",
    title: "Banjir Genangan di Jl. Veteran",
    category: "Drainase & Banjir",
    categoryId: "4",
    description: "Jalan Veteran terendam banjir setinggi 40-60 cm setiap kali hujan deras. Menghambat aktivitas warga dan merusak kendaraan.",
    location: "Jl. Veteran, Kediri",
    district: "Mojoroto",
    date: "2024-12-13",
    status: "Diproses",
    priority: "Tinggi",
    agency: "BPBD",
    agencyCode: "BPBD",
    reporter: "Anonim2905817364",
    isAnonymous: true,
    photos: [
      "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&h=500&fit=crop&auto=format",
    ],
    supportCount: 156,
    commentCount: 28,
    isSupported: true,
    isSaved: true,
    lat: -7.822,
    lng: 112.007,
    timeline: [
      { status: "Dikirim", date: "13 Des 2024", time: "11:30", description: "Laporan dikirim oleh warga" },
      { status: "Diverifikasi", date: "14 Des 2024", time: "09:00", description: "Laporan diverifikasi oleh Admin BPBD", actor: "Admin BPBD" },
      { status: "Diproses", date: "14 Des 2024", time: "13:00", description: "Tim sedang mengkaji solusi drainase permanen", actor: "Admin BPBD" },
    ],
    governmentResponse: "Permasalahan banjir genangan sedang dalam proses penanganan. Kami akan melakukan normalisasi saluran drainase di area Jl. Veteran.",
    responseDate: "15 Des 2024",
  },
];

export const users: User[] = [
  { id: "1", name: "Anonim7283640192", phone: "081234567890", email: "anon1@aspiaku.go.id", role: "masyarakat", status: "Aktif", lastLogin: "2024-12-19 08:45", totalReports: 8, completedReports: 5, isVerified: true },
  { id: "2", name: "Anonim3847562910", phone: "082345678901", email: "anon2@aspiaku.go.id", role: "masyarakat", status: "Aktif", lastLogin: "2024-12-18 15:20", totalReports: 3, completedReports: 2, isVerified: true },
  { id: "3", name: "Anonim6192847305", phone: "085678901234", email: "anon3@aspiaku.go.id", role: "masyarakat", status: "Aktif", lastLogin: "2024-12-17 10:00", totalReports: 12, completedReports: 9, isVerified: true },
  { id: "4", name: "Anonim9047251836", phone: "087890123456", email: "anon4@aspiaku.go.id", role: "masyarakat", status: "Aktif", lastLogin: "2024-12-19 07:30", totalReports: 4, completedReports: 3, isVerified: false },
  { id: "5", name: "Admin PUPR", phone: "081100000001", email: "admin@pupr.go.id", role: "admin_instansi", agency: "Dinas PUPR", agencyCode: "PUPR", status: "Aktif", lastLogin: "2024-12-19 07:55", isVerified: true },
  { id: "6", name: "Admin DLH", phone: "081100000002", email: "admin@dlh.go.id", role: "admin_instansi", agency: "Dinas Lingkungan Hidup", agencyCode: "DLH", status: "Aktif", lastLogin: "2024-12-18 16:00", isVerified: true },
  { id: "7", name: "Rizky Firmansyah", phone: "081100000010", email: "superadmin@aspiaku.go.id", role: "super_admin", status: "Aktif", lastLogin: "2024-12-19 08:00", isVerified: true },
  { id: "8", name: "Teguh Wibowo", phone: "081100000011", email: "server@aspiaku.go.id", role: "admin_server", status: "Aktif", lastLogin: "2024-12-19 06:00", isVerified: true },
  { id: "9", name: "Indra Kusuma", phone: "081100000012", email: "sistem@aspiaku.go.id", role: "admin_sistem", status: "Aktif", lastLogin: "2024-12-19 06:30", isVerified: true },
];

export const notifications: Notification[] = [
  { id: "1", type: "processing", title: "Laporan Sedang Diproses", message: "Laporan RPT-2024-001 tentang Jalan Berlubang di Banyakan kini sedang dalam proses penanganan.", reportId: "RPT-2024-001", timestamp: "17 Des 2024, 09:00", isRead: false },
  { id: "2", type: "response", title: "Pemerintah Memberikan Tanggapan", message: "Dinas PUPR telah memberikan tanggapan resmi untuk laporan Anda.", reportId: "RPT-2024-001", timestamp: "17 Des 2024, 09:05", isRead: false },
  { id: "3", type: "verified", title: "Laporan Diverifikasi", message: "Laporan RPT-2024-003 tentang Lampu PJU Mati telah diverifikasi oleh Admin PUPR.", reportId: "RPT-2024-003", timestamp: "11 Des 2024, 08:30", isRead: true },
  { id: "4", type: "completed", title: "Laporan Selesai", message: "Laporan RPT-2024-004 tentang Saluran Air Tersumbat telah berhasil ditangani.", reportId: "RPT-2024-004", timestamp: "05 Des 2024, 16:30", isRead: true },
  { id: "5", type: "received", title: "Laporan Diterima", message: "Laporan RPT-2024-008 tentang Banjir Genangan di Jl. Veteran telah diterima sistem.", reportId: "RPT-2024-008", timestamp: "13 Des 2024, 11:30", isRead: true },
];

export const auditLogs: AuditLog[] = [
  { id: "1", timestamp: "2024-12-19 08:32:15", user: "Admin PUPR", action: "Verifikasi Laporan", module: "Laporan", ip: "192.168.1.10", device: "Chrome/Windows", status: "Berhasil" },
  { id: "2", timestamp: "2024-12-19 08:15:00", user: "Rizky Firmansyah", action: "Login", module: "Auth", ip: "192.168.1.5", device: "Firefox/Mac", status: "Berhasil" },
  { id: "3", timestamp: "2024-12-19 07:55:42", user: "Admin PUPR", action: "Login", module: "Auth", ip: "192.168.1.10", device: "Chrome/Windows", status: "Berhasil" },
  { id: "4", timestamp: "2024-12-18 17:30:00", user: "Rizky Firmansyah", action: "Tambah Instansi", module: "Instansi", ip: "192.168.1.5", device: "Firefox/Mac", status: "Berhasil" },
  { id: "5", timestamp: "2024-12-18 16:10:00", user: "Admin DLH", action: "Tolak Laporan", module: "Laporan", ip: "192.168.1.12", device: "Chrome/Linux", status: "Berhasil" },
  { id: "6", timestamp: "2024-12-18 15:45:00", user: "Unknown", action: "Login", module: "Auth", ip: "10.0.0.99", device: "curl/7.68", status: "Gagal" },
  { id: "7", timestamp: "2024-12-18 14:00:00", user: "Teguh Wibowo", action: "Backup Database", module: "Server", ip: "127.0.0.1", device: "System", status: "Berhasil" },
  { id: "8", timestamp: "2024-12-18 12:00:00", user: "Indra Kusuma", action: "Update Konfigurasi", module: "Sistem", ip: "192.168.1.20", device: "Safari/Mac", status: "Berhasil" },
];

export const routingRules: RoutingRule[] = [
  { id: "1", category: "Jalan & Infrastruktur", agency: "Dinas PUPR", priority: "Tinggi", status: "Aktif" },
  { id: "2", category: "Kebersihan & Sampah", agency: "Dinas Lingkungan Hidup", priority: "Sedang", status: "Aktif" },
  { id: "3", category: "Penerangan Jalan", agency: "Dinas PUPR", priority: "Sedang", status: "Aktif" },
  { id: "4", category: "Drainase & Banjir", agency: "BPBD", priority: "Tinggi", status: "Aktif" },
  { id: "5", category: "Pohon & Taman", agency: "Dinas Lingkungan Hidup", priority: "Rendah", status: "Aktif" },
  { id: "6", category: "Trotoar & Fasilitas", agency: "Dinas PUPR", priority: "Sedang", status: "Aktif" },
  { id: "7", category: "Bencana Alam", agency: "BPBD", priority: "Urgent", status: "Aktif" },
  { id: "8", category: "Lingkungan & Polusi", agency: "Dinas Lingkungan Hidup", priority: "Tinggi", status: "Aktif" },
];

export const monthlyStats = [
  { bulan: "Jul", laporan: 42, selesai: 31 },
  { bulan: "Agu", laporan: 58, selesai: 44 },
  { bulan: "Sep", laporan: 51, selesai: 39 },
  { bulan: "Okt", laporan: 67, selesai: 52 },
  { bulan: "Nov", laporan: 74, selesai: 58 },
  { bulan: "Des", laporan: 65, selesai: 28 },
];

export const statusDistribution = [
  { name: "Dikirim", value: 48, color: "#0ea5e9" },
  { name: "Diverifikasi", value: 32, color: "#3b82f6" },
  { name: "Diproses", value: 41, color: "#f59e0b" },
  { name: "Selesai", value: 183, color: "#10b981" },
  { name: "Ditolak", value: 23, color: "#ef4444" },
];

export const categoryDistribution = [
  { name: "Jalan & Infrastruktur", laporan: 87 },
  { name: "Kebersihan & Sampah", laporan: 64 },
  { name: "Penerangan Jalan", laporan: 45 },
  { name: "Drainase & Banjir", laporan: 38 },
  { name: "Trotoar & Fasilitas", laporan: 33 },
  { name: "Pohon & Taman", laporan: 29 },
];

export const agencyPerformance = [
  { instansi: "PUPR", total: 142, selesai: 98, responsTime: 2.1 },
  { instansi: "DLH", total: 89, selesai: 67, responsTime: 1.8 },
  { instansi: "BPBD", total: 56, selesai: 48, responsTime: 0.8 },
  { instansi: "DISHUB", total: 38, selesai: 29, responsTime: 3.2 },
  { instansi: "DINSOS", total: 21, selesai: 15, responsTime: 4.1 },
];
